## Curious why I'm not using Helm hooks?
## It's because I don't feel like editing 
## MinIO's chart. 
apiVersion: v1
kind: Pod
metadata:
    name: debug
    labels:
      name: debug
spec:
    containers:
      - name: init-storage
        image: {{ docker_server }}/ai:{{ ai_image_tag }}
        env:
          - name: MINIO_ACCESSKEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: accesskey
          - name: MINIO_SECRETKEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: secretkey
          - name: POSTGRES_SECRET
            valueFrom:
              secretKeyRef:
                name: postgres
                key: postgres-secret
        command: 
          - "python3"
          - "-u"
          - "/app/src/python/debug/debug_mode.py"
        volumeMounts: 
          - name: models-vol
            mountPath: /models
        imagePullPolicy: Always
    imagePullSecrets:
      - name: acr-creds
    volumes:
      - name: models-vol
        emptyDir: {} 
