apiVersion: v1 
kind: Pod 
metadata: 
    name: {{ .Values.name }} 
    labels:
      name: {{ .Values.name }} 
spec: 
    containers: 
      - name: {{ .Values.name }} 
        image: {{ .Values.docker_server }}/phase-2:v0.0.1
        command: ["bash", "/app/src/scripts/run-navigate-dense.sh"]
        imagePullPolicy: Always
    imagePullSecrets:
      - name: acr-creds
    nodeSelector: 
      agentpool: default 
