apiVersion: v1 
kind: Pod 
metadata: 
    name: {{ .Values.name }} 
    labels:
      name: {{ .Values.name }} 
spec: 
    containers: 
      - name: {{ .Values.name }} 
        image: {{ .Values.docker_server }}/ai:{{ .Values.ai_image_tag }} 
        command: ["bash", "/app/src/scripts/run-navigate-dense.sh"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2000Mi"
            cpu: "1000m"
    imagePullSecrets:
      - name: acr-creds
    nodeSelector: 
      agentpool: default 
