apiVersion: apps/v1 
kind: Deployment
metadata: 
    name: {{ .Values.name }} 
    labels:
      name: {{ .Values.name }}
      app: simulation 
spec:
  replicas: {{ .Values.replicas }} 
  selector:
    matchLabels:
      app: simulation 
  template:
    metadata:
      labels:
        name: {{ .Values.name }} 
        app: simulation
    spec: 
      containers: 
        - name: {{ .Values.name }} 
          image: {{ .Values.docker_server }}/ai:v0.0.1
          env:
            - name: DISTRIBUTED_ROLE 
              value: SIMULATION
            - name: MINIO_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: accesskey 
            - name: MINIO_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secretkey
            - name: POSTGRES_SECRET 
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: postgres-secret 
          command: ["bash", "/app/src/scripts/run-navigate-dense.sh"]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1500m"
      imagePullSecrets:
        - name: acr-creds
      nodeSelector: 
        agentpool: ephemeral 
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Exists" 
